version: "3.9"

networks:
  fm-project-network:
    driver: bridge
services:
      fm-project-mysql:
        image: mysql:8.0
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - "3306:3306"
        networks:
          - fm-project-network
      fm-project-api:
        image: josiassxz/fm-project
        environment:
          DB_HOST: "fm-project-mysql"
        ports:
          - "8080:8080"
        networks:
         - fm-project-network
        depends_on:
         - fm-project-mysql